
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nabil Rizki
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setJam();
        setTanggal();
        setKasir();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Jam1 = new javax.swing.JLabel();
        Kasir1 = new javax.swing.JLabel();
        Tanggal1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelData = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        BtnClear = new javax.swing.JButton();
        BtnTambah = new javax.swing.JButton();
        txtBarang = new javax.swing.JTextField();
        txtHargaBarang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtIdBarang = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBanyakBarang = new javax.swing.JTextField();
        jbDelete = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtBayar = new javax.swing.JTextField();
        txtKembali = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtDisc = new javax.swing.JLabel();
        txtPrint = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtHitung = new javax.swing.JButton();
        txtPrint1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Adobe Caslon Pro", 1, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RESTORAN BUDI ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 270, 30);

        jLabel2.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("jl. Saudi Arabic no 21 ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 40, 220, 16);

        Jam1.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        Jam1.setForeground(new java.awt.Color(255, 255, 255));
        Jam1.setText("Jam");
        jPanel1.add(Jam1);
        Jam1.setBounds(750, 24, 90, 30);

        Kasir1.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        Kasir1.setForeground(new java.awt.Color(255, 255, 255));
        Kasir1.setText("Nama Kasir");
        jPanel1.add(Kasir1);
        Kasir1.setBounds(450, 24, 90, 30);

        Tanggal1.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        Tanggal1.setForeground(new java.awt.Color(255, 255, 255));
        Tanggal1.setText("Tanggal");
        jPanel1.add(Tanggal1);
        Tanggal1.setBounds(590, 24, 120, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 910, 70);

        TabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Barang", "Nama Barang", "Banyak Barang", "Harga Barang", "Jumlah"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelData);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(440, 70, 452, 190);

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));
        jPanel2.setLayout(null);

        BtnClear.setText("Clear");
        BtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearActionPerformed(evt);
            }
        });
        jPanel2.add(BtnClear);
        BtnClear.setBounds(150, 310, 130, 40);

        BtnTambah.setText("Tambah");
        BtnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambahActionPerformed(evt);
            }
        });
        jPanel2.add(BtnTambah);
        BtnTambah.setBounds(10, 310, 130, 40);
        jPanel2.add(txtBarang);
        txtBarang.setBounds(120, 110, 300, 40);
        jPanel2.add(txtHargaBarang);
        txtHargaBarang.setBounds(120, 160, 300, 40);

        jLabel4.setFont(new java.awt.Font("Humnst777 BT", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Harga Barang");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 160, 110, 40);

        jLabel7.setFont(new java.awt.Font("Humnst777 BT", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nama Barang");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 110, 110, 40);

        jLabel8.setFont(new java.awt.Font("Humnst777 BT", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID Barang");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 60, 110, 40);

        txtIdBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdBarangActionPerformed(evt);
            }
        });
        jPanel2.add(txtIdBarang);
        txtIdBarang.setBounds(120, 60, 300, 40);

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel2.add(txtId);
        txtId.setBounds(120, 10, 300, 40);

        jLabel9.setFont(new java.awt.Font("Humnst777 BT", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ID Transaksi");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 10, 110, 40);

        jLabel6.setFont(new java.awt.Font("Humnst777 BT", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Banyak Barang");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 210, 110, 40);
        jPanel2.add(txtBanyakBarang);
        txtBanyakBarang.setBounds(120, 210, 300, 40);

        jbDelete.setText("Delete");
        jbDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(jbDelete);
        jbDelete.setBounds(290, 310, 130, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 70, 440, 380);

        jPanel3.setBackground(new java.awt.Color(0, 102, 255));
        jPanel3.setLayout(null);
        jPanel3.add(txtBayar);
        txtBayar.setBounds(70, 50, 200, 30);
        jPanel3.add(txtKembali);
        txtKembali.setBounds(70, 90, 200, 30);

        jLabel11.setFont(new java.awt.Font("Humnst777 BT", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Kembali");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(10, 90, 110, 30);

        jLabel10.setFont(new java.awt.Font("Humnst777 BT", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Bayar ");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 50, 110, 30);

        txtDisc.setFont(new java.awt.Font("Humnst777 BT", 0, 12)); // NOI18N
        txtDisc.setForeground(new java.awt.Color(255, 255, 255));
        txtDisc.setText("Disc. 0%");
        jPanel3.add(txtDisc);
        txtDisc.setBounds(290, 50, 110, 30);

        txtPrint.setText("Total");
        txtPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrintActionPerformed(evt);
            }
        });
        jPanel3.add(txtPrint);
        txtPrint.setBounds(280, 10, 160, 30);

        jLabel12.setFont(new java.awt.Font("Humnst777 BT", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Total");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(10, 10, 110, 30);

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        jPanel3.add(txtTotal);
        txtTotal.setBounds(70, 10, 200, 30);

        txtHitung.setText("Hitung");
        txtHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHitungActionPerformed(evt);
            }
        });
        jPanel3.add(txtHitung);
        txtHitung.setBounds(280, 90, 160, 30);

        txtPrint1.setText("Print");
        txtPrint1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrint1ActionPerformed(evt);
            }
        });
        jPanel3.add(txtPrint1);
        txtPrint1.setBounds(280, 130, 160, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(440, 260, 450, 190);

        setSize(new java.awt.Dimension(908, 486));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClearActionPerformed
        // TODO add your handling code here:
        txtId.setText("");
        txtIdBarang.setText("");
        txtBarang.setText("");
        txtBanyakBarang.setText("");
        txtHargaBarang.setText("");
    }//GEN-LAST:event_BtnClearActionPerformed

    private void BtnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambahActionPerformed
        // TODO add your handling code here:
        int transaksi = Integer.parseInt(txtId.getText());
        int banyak = Integer.parseInt(txtBanyakBarang.getText());
        int harga = Integer.parseInt(txtHargaBarang.getText());
        int jumlah = banyak * harga;
        if ("".equals(txtBarang.getText()) || "".equals(txtBanyakBarang.getText()) || "".equals(txtHargaBarang.getText())) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {

            String SQL = "INSERT INTO tb_barang (id_barang,nama_barang,banyak_barang,harga_barang,jumlah) "
            + "VALUES('" + txtIdBarang.getText() + "','" + txtBarang.getText() + "'," + banyak + "," + harga + ","
            + jumlah + ")";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","Sukses",JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_BtnTambahActionPerformed

    private void txtIdBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdBarangActionPerformed

    private void jbDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeleteActionPerformed
        // TODO add your handling code here:
        int baris = TabelData.getSelectedRow();
        if (baris != -1) {
            String id = TabelData.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_barang WHERE id_barang='"+id+"'";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jbDeleteActionPerformed

    private void txtHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHitungActionPerformed
        // TODO add your handling code here:
        int bayar = Integer.parseInt(txtBayar.getText());
        int total = Integer.parseInt(txtTotal.getText());
        int kembali = bayar-total;
        txtKembali.setText(kembali+"");
    }//GEN-LAST:event_txtHitungActionPerformed

    private void txtPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrintActionPerformed
       totalHarga();
    }//GEN-LAST:event_txtPrintActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtPrint1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrint1ActionPerformed
        // TODO add your handling code here:
         MessageFormat header = new MessageFormat("Transaksi Pembelian");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}     ");
        try {
            TabelData.print(JTable.PrintMode.FIT_WIDTH,header,footer,true,null,true,null);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_txtPrint1ActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnClear;
    private javax.swing.JButton BtnTambah;
    private javax.swing.JLabel Jam1;
    private javax.swing.JLabel Kasir1;
    private javax.swing.JTable TabelData;
    private javax.swing.JLabel Tanggal1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbDelete;
    private javax.swing.JTextField txtBanyakBarang;
    private javax.swing.JTextField txtBarang;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JLabel txtDisc;
    private javax.swing.JTextField txtHargaBarang;
    private javax.swing.JButton txtHitung;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdBarang;
    private javax.swing.JTextField txtKembali;
    private javax.swing.JButton txtPrint;
    private javax.swing.JButton txtPrint1;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
       String kolom[] = {"ID Barang","Nama Barang","Banyak Barang","Harga Barang","Jumlah"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tb_barang";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        
        try
        {
            while(rs.next())
            {
                String IDBarang = rs.getString(1);
                String NamaBarang = rs.getString(2);
                String BanyakBarang = rs.getString(3);
                String Harga = rs.getString(4);
                String Jumlah = rs.getString(5);
                String data[] = {IDBarang,NamaBarang,BanyakBarang,Harga,Jumlah};
                dtm.addRow(data);
            }
        }
        catch(SQLException ex)
        {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        TabelData.setModel(dtm);
    }
    
    private void setJam() {
    {
        ActionListener taskPerformer = new ActionListener()
        {
            public void actionPerformed(ActionEvent evt)
            {
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                String nol_jam = "";
                String nol_menit = "";
                String nol_detik = "";
                if(nilai_jam<=9)
                {
                    nol_jam="0";
                }
                if(nilai_menit<=9)
                {
                    nol_menit="0";
                }
                if(nilai_detik<=9)
                {
                    nol_detik="0";
                }
                String jam = nol_jam+Integer.toString(nilai_jam);
                String menit = nol_menit+Integer.toString(nilai_menit);
                String detik = nol_detik+Integer.toString(nilai_detik);
                Jam1.setText(jam+":"+menit+":"+detik);
            }
        };
        new Timer(100, taskPerformer).start();
    } //To change body of generated methods, choose Tools | Templates.
    }

    private void setTanggal() {
        java.util.Date skrg = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd-MM-yyyy");
        Tanggal1.setText(kal.format(skrg));
    }

    private void setKasir() {
         String SQL = "SELECT * FROM tb_akun";
        ResultSet result = KoneksiDB.executeQuery(SQL);
        try {
            while(result.next()){
                String namaKasir = result.getString(1);
                Kasir1.setText(namaKasir);
            }
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void totalHarga() {
        int banyak = TabelData.getRowCount();
        int hasil = 0;
        for (int i = 0; i < banyak; i++) {
            hasil += Integer.parseInt(TabelData.getValueAt(i, 4).toString());
        }
        if (hasil > 200000) {
            int disc = (int) (hasil * 0.15);
            hasil -= disc;
            txtDisc.setText("Disc. 30%");
        }
        txtTotal.setText(String.valueOf(hasil));
    }
}


